# MySQL Veritabanı Bağlantısı
spring.datasource.url=jdbc:mysql://localhost:3306/sip_core_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Baba6638.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Sunucu Portu
server.port=8080

# --- GMAIL SMTP AYARLARI (OTOMATİK MAİL SİSTEMİ) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ahmetcanbozkurt295@gmail.com
spring.mail.password=laty tciq ifcj gcwp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true